"""Shared Calaos/Case 2.0 .smbp XML builder for Schneider M221 exports."""

from __future__ import annotations

import re
from html import escape
from pathlib import Path
from typing import Any

from ...schemas.ir import PlcProgram
from ...schemas.m221 import M221ProgramData
from ..m221_adapter import plc_program_to_m221_data

SAMPLES_DIR = Path(__file__).resolve().parents[3] / "samples"
CALAOS_TEMPLATE = SAMPLES_DIR / "tankcontrol.smbp"

CALAOS_STRUCTURE_MARKERS = (
    'xmlns="http://www.schneider-electric.com/Calaos/Case/2.0"',
    '<FileHeader Company="Schneider Electric"',
    "<Workspace>",
    "<Project>",
    "<body>",
    "<LD>",
    "<Rungs>",
    "<Configuration>",
    '<GlobalVars name="GlobalVariables">',
)

IL_ELEMENT_MAP = {
    "LD": ("NormalContact", False),
    "LDN": ("NegatedContact", False),
    "AND": ("NormalContact", False),
    "ANDN": ("NegatedContact", False),
    "OR": ("NormalContact", False),
    "ORN": ("NegatedContact", False),
    "ST": ("Coil", False),
    "S": ("SetCoil", False),
    "R": ("ResetCoil", False),
    "IN": ("TimerFunctionBlock", False),
}


def render_calaos_smbp_from_program(program: PlcProgram, plc_model: str) -> str:
    data = M221ProgramData.model_validate(plc_program_to_m221_data(program))
    return render_calaos_smbp_from_data(data, plc_model)


def render_calaos_smbp_from_data(data: M221ProgramData, plc_model: str) -> str:
    if not CALAOS_TEMPLATE.is_file():
        raise FileNotFoundError(f"Calaos template not found: {CALAOS_TEMPLATE}")

    content = CALAOS_TEMPLATE.read_text(encoding="utf-8")
    pou_name = _sanitize_name(data.projectName)
    content = _replace_project_metadata(content, data.projectName, pou_name, plc_model)
    content = _replace_local_vars(content, data)
    content = _replace_global_vars(content, data)
    content = _replace_rungs(content, data)
    return content


def calaos_structure_markers_present(content: str) -> bool:
    return all(marker in content for marker in CALAOS_STRUCTURE_MARKERS)


def _sanitize_name(name: str) -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9_]", "_", name.strip()) or "Main_Program"
    if cleaned[0].isdigit():
        cleaned = f"P_{cleaned}"
    return cleaned


def _replace_project_metadata(content: str, project_name: str, pou_name: str, plc_model: str) -> str:
    content = re.sub(
        r"(<ContentHeader Name=\")[^\"]+(\")",
        rf'\1{escape(project_name)}.smbp\2',
        content,
        count=1,
    )
    content = re.sub(
        r"(<Comment>)[^<]*(</Comment>\s*</ContentHeader>)",
        rf"\1Generated by PLCAutoPilot\2",
        content,
        count=1,
    )
    content = re.sub(
        r'(<Node Name=")[^"]+(" />)',
        rf'\1{escape(pou_name)}\2',
        content,
        count=1,
    )
    content = re.sub(
        r'(<POU Name=")[^"]+(" Type="program">)',
        rf'\1{escape(pou_name)}\2',
        content,
        count=1,
    )
    content = re.sub(
        r"(<Device>\s*<Name>)[^<]+(</Name>)",
        rf"\1{escape(plc_model)}\2",
        content,
        count=1,
    )
    return content


def _variable_xml(name: str, comment: str, address: str | None = None, var_type: str = "BOOL") -> str:
    type_tag = "TIMER" if var_type == "TIMER" else "BOOL"
    address_line = f"\n            <address>{escape(address)}</address>" if address else ""
    return f"""          <variable name="{escape(name)}">
            <type>
              <{type_tag} />
            </type>
            <initialValue>
              <simpleValue value="FALSE" />
            </initialValue>
            <comment>{escape(comment)}</comment>{address_line}
          </variable>"""


def _replace_local_vars(content: str, data: M221ProgramData) -> str:
    variables: list[str] = []
    seen: set[str] = set()

    for group in (data.inputs, data.outputs, data.memory):
        for point in group:
            if point.symbol in seen:
                continue
            seen.add(point.symbol)
            variables.append(_variable_xml(point.symbol, point.comment or point.symbol))

    block = "<localVars>\n" + "\n".join(variables) + "\n        </localVars>"
    return re.sub(r"<localVars>.*?</localVars>", block, content, count=1, flags=re.DOTALL)


def _replace_global_vars(content: str, data: M221ProgramData) -> str:
    variables: list[str] = []

    for point in data.memory:
        variables.append(_variable_xml(point.symbol, point.comment or point.symbol, point.address))

    for timer in data.timers:
        variables.append(_variable_xml(timer.symbol, timer.comment or timer.symbol, timer.address, "TIMER"))

    if not variables:
        variables.append(_variable_xml("SEQUENCE_RUN", "Internal memory bit", "%M0"))

    block = '<GlobalVars name="GlobalVariables">\n' + "\n".join(variables) + "\n    </GlobalVars>"
    return re.sub(r'<GlobalVars name="GlobalVariables">.*?</GlobalVars>', block, content, count=1, flags=re.DOTALL)


def _replace_rungs(content: str, data: M221ProgramData) -> str:
    rungs_xml = "\n".join(_build_rung_xml(rung, index) for index, rung in enumerate(data.rungs, start=1))
    block = f"<Rungs>\n{rungs_xml}\n        </Rungs>"
    return re.sub(r"<Rungs>.*?</Rungs>", block, content, count=1, flags=re.DOTALL)


def _build_rung_xml(rung: Any, index: int) -> str:
    ladder_elements = _il_to_ladder_elements(rung.il)
    instruction_lines = "".join(
        f"""
              <InstructionLineEntity>
                <InstructionLine>{escape(line.strip())}</InstructionLine>
                <Comment></Comment>
              </InstructionLineEntity>"""
        for line in rung.il
    )
    return f"""          <RungEntity>
            <LadderElements>
{ladder_elements}
            </LadderElements>
            <InstructionLines>{instruction_lines}
            </InstructionLines>
            <Name>Rung {index}</Name>
            <MainComment>{escape(rung.comment or rung.name)}</MainComment>
            <Label />
            <IsLadderSelected>true</IsLadderSelected>
          </RungEntity>"""


def _il_to_ladder_elements(il_lines: list[str]) -> str:
    elements: list[str] = []
    column = 0

    for line in il_lines:
        parts = line.strip().split()
        if not parts:
            continue
        instruction = parts[0].upper()
        operand = parts[1] if len(parts) > 1 else ""

        if instruction in {"BLK", "OUT_BLK", "END_BLK"}:
            continue
        if instruction == "Q" and operand == "":
            operand = "Q"

        mapped = IL_ELEMENT_MAP.get(instruction)
        if not mapped:
            continue

        element_type, _ = mapped
        symbol = _symbol_from_operand(operand)
        elements.append(
            f"""              <LadderEntity>
                <ElementType>{element_type}</ElementType>
                <Descriptor>{escape(operand)}</Descriptor>
                <Comment>{escape(instruction)} {escape(operand)}</Comment>
                <Symbol>{escape(symbol)}</Symbol>
                <Row>0</Row>
                <Column>{column}</Column>
                <ChosenConnection>Left, Right</ChosenConnection>
              </LadderEntity>"""
        )
        column += 1

    while column < 10:
        elements.append(
            f"""              <LadderEntity>
                <ElementType>Line</ElementType>
                <Row>0</Row>
                <Column>{column}</Column>
                <ChosenConnection>Left, Right</ChosenConnection>
              </LadderEntity>"""
        )
        column += 1

    return "\n".join(elements)


def _symbol_from_operand(operand: str) -> str:
    if not operand or operand == "Q":
        return ""
    if operand.startswith("%"):
        return operand.replace(".", "_").replace("%", "")
    return operand
