"""Helpers for golden IR fixtures and export hash regression tests."""

from __future__ import annotations

import hashlib
import io
import json
import re
import zipfile
from copy import deepcopy
from pathlib import Path
from typing import Any

from api.ir.patterns import build_pattern
from api.services.ir_service import IrService

FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures"
IR_FIXTURES_DIR = FIXTURES_DIR / "ir"
EXPORT_MANIFEST_PATH = FIXTURES_DIR / "exports" / "manifest.json"

IR_FIXTURE_CASES: list[dict[str, Any]] = [
    {
        "id": "motor_startstop_schneider",
        "pattern": "motor_startstop",
        "vendor": "schneider",
        "model": "TM221CE24R",
        "projectName": "Golden_Motor_Schneider",
    },
    {
        "id": "motor_startstop_rockwell",
        "pattern": "motor_startstop",
        "vendor": "rockwell",
        "model": "1769-L33ER",
        "projectName": "Golden_Motor_Rockwell",
    },
    {
        "id": "sequential_lights_schneider",
        "pattern": "sequential_lights",
        "vendor": "schneider",
        "model": "TM221CE16T",
        "projectName": "Golden_Seq_Schneider",
        "numLights": 4,
        "delaySeconds": 3,
    },
    {
        "id": "sequential_lights_rockwell",
        "pattern": "sequential_lights",
        "vendor": "rockwell",
        "model": "1769-L33ER",
        "projectName": "Golden_Seq_Rockwell",
        "numLights": 4,
        "delaySeconds": 3,
    },
]

EXPORT_CASES: list[dict[str, Any]] = [
    *IR_FIXTURE_CASES,
    {
        "id": "motor_startstop_siemens",
        "pattern": "motor_startstop",
        "vendor": "siemens",
        "model": "S7-1200",
        "projectName": "Golden_Motor_Siemens",
    },
    {
        "id": "motor_startstop_mitsubishi",
        "pattern": "motor_startstop",
        "vendor": "mitsubishi",
        "model": "FX5U",
        "projectName": "Golden_Motor_Mitsubishi",
    },
    {
        "id": "plcopen_motor_codesys",
        "pattern": "motor_startstop",
        "vendor": "codesys",
        "model": "Generic",
        "projectName": "MotorControl_Universal",
        "plcopen": True,
    },
]


def normalize_ir_program(program: dict[str, Any]) -> dict[str, Any]:
    normalized = deepcopy(program)
    meta = normalized.get("meta")
    if isinstance(meta, dict) and "createdAt" in meta:
        meta["createdAt"] = "2000-01-01T00:00:00+00:00"
    return normalized


def build_ir_program(case: dict[str, Any]) -> dict[str, Any]:
    program = build_pattern(
        case["pattern"],
        project_name=case["projectName"],
        vendor=case["vendor"],
        model=case["model"],
        num_lights=int(case.get("numLights", 4)),
        delay_seconds=int(case.get("delaySeconds", 3)),
    )
    return normalize_ir_program(program.model_dump())


def normalize_export_text(text: str, export_format: str) -> str:
    normalized = text.replace("\r\n", "\n")
    normalized = re.sub(r'ExportDate="[^"]+"', 'ExportDate="FIXED"', normalized)
    normalized = re.sub(r'creationDateTime="[^"]+"', 'creationDateTime="FIXED"', normalized)
    normalized = re.sub(
        r"(<Comment>)Generated by PLCAutoPilot[^<]*(</Comment>)",
        r"\1Generated by PLCAutoPilot\2",
        normalized,
    )
    if export_format == "machine_expert_basic_xml":
        normalized = re.sub(
            r'(<ContentHeader Name=")[^"]+\.smbp(")',
            r"\1Golden.smbp\2",
            normalized,
            count=1,
        )
    return normalized


def normalize_export_bytes(content: bytes, export_format: str) -> bytes:
    if export_format == "mitsubishi_tier2_zip":
        parts: list[str] = []
        with zipfile.ZipFile(io.BytesIO(content)) as archive:
            for name in sorted(archive.namelist()):
                member = archive.read(name).decode("utf-8")
                member_format = "il" if name.endswith(".il") else "st" if name.endswith(".st") else "csv"
                normalized = normalize_export_text(member, member_format)
                parts.append(f"{name}:{sha256_bytes(normalized.encode('utf-8'))}")
        return "\n".join(parts).encode("utf-8")

    text = content.decode("utf-8")
    return normalize_export_text(text, export_format).encode("utf-8")


def sha256_bytes(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def serialize_export_case(service: IrService, case: dict[str, Any]) -> tuple[bytes, str]:
    if case.get("plcopen"):
        payload = service.get_pattern_ir(
            case["pattern"],
            project_name=case["projectName"],
            vendor=case["vendor"],
            model=case["model"],
            num_lights=int(case.get("numLights", 4)),
            delay_seconds=int(case.get("delaySeconds", 3)),
        )
        program = payload["program"]
        program["target"] = {"vendor": case["vendor"], "model": case["model"]}
        result = service.serialize_plcopen(program)
        export_format = "plcopen_xml"
    else:
        payload = service.get_pattern_ir(
            case["pattern"],
            project_name=case["projectName"],
            vendor=case["vendor"],
            model=case["model"],
            num_lights=int(case.get("numLights", 4)),
            delay_seconds=int(case.get("delaySeconds", 3)),
        )
        result = service.serialize(payload["program"])
        export_format = str(result["metadata"].get("format", "unknown"))

    import base64

    content = base64.standard_b64decode(result["contentBase64"])
    return content, export_format


def export_hash(service: IrService, case: dict[str, Any]) -> str:
    content, export_format = serialize_export_case(service, case)
    normalized = normalize_export_bytes(content, export_format)
    return sha256_bytes(normalized)


def load_export_manifest() -> dict[str, Any]:
    return json.loads(EXPORT_MANIFEST_PATH.read_text(encoding="utf-8"))


def write_export_manifest(entries: dict[str, dict[str, str]]) -> None:
    EXPORT_MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    manifest = {
        "version": 1,
        "exports": entries,
    }
    EXPORT_MANIFEST_PATH.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def write_ir_fixtures() -> None:
    IR_FIXTURES_DIR.mkdir(parents=True, exist_ok=True)
    for case in IR_FIXTURE_CASES:
        path = IR_FIXTURES_DIR / f"{case['id']}.json"
        path.write_text(json.dumps(build_ir_program(case), indent=2) + "\n", encoding="utf-8")


def refresh_all_golden_fixtures() -> None:
    service = IrService()
    write_ir_fixtures()
    entries: dict[str, dict[str, str]] = {}
    for case in EXPORT_CASES:
        content, export_format = serialize_export_case(service, case)
        normalized = normalize_export_bytes(content, export_format)
        entries[case["id"]] = {
            "sha256": sha256_bytes(normalized),
            "format": export_format,
        }
    write_export_manifest(entries)
